name: obvious
description: A collection of useful classes and extensions so obvious you'll wonder why they aren't offical
version: 0.1.0+1


environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
